# Generated by Django 5.0.6 on 2024-06-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('feriado', 'Feriado'), ('evento_escolar', 'Evento Escolar'), ('reuniao', 'Reunião')], max_length=20)),
            ],
        ),
    ]
