# Generated by Django 5.0.6 on 2024-06-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('feriado', 'Feriado'), ('evento', 'Evento'), ('reuniao', 'Reunião')], max_length=20),
        ),
    ]
