# Generated by Django 5.0.6 on 2024-06-18 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('historico', 'Histórico Escolar'), ('declaracao', 'Declaração de Matrícula'), ('boletim', 'Boletim Escolar'), ('atestado', 'Atestado de Matrícula'), ('certificado', 'Certificado de Conclusão'), ('contagem', 'Contagem de Tempo'), ('ata', 'Ata de Reunião de Pais'), ('outros', 'Outros')], max_length=20)),
                ('data_emissao', models.DateField()),
                ('conteudo', models.TextField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
            ],
        ),
    ]
